Enlist Cosmos DB scaler on Artifact Hub
kedacore/external-scalers pull request #10
Opened 2021-11-10 12:42 UTC by JatinSanghvi

Add package for 'KEDA external scaler for Azure Cosmos DB' in 'KEDA Official External Scalers' repository on Artifact Hub. The package is intended for current `experimental` version of the scaler. We would enlist a new package version, once a versioned-release for the the scaler is out.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Fixes https://github.com/kedacore/keda-external-scaler-azure-cosmos-db/issues/7

2021-11-10 12:54 UTC, tomkerkhove requested changes
We'll need a bit more docs

2021-11-10 12:54 UTC, tomkerkhove commented on artifacthub/azure-cosmos-db/0.0.1/README.md
> +Please refer to the [official Readme on GitHub](https://github.com/kedacore/keda-external-scaler-azure-cosmos-db#readme) for setup instructions to be able to leverage KEDA and KEDA external scaler fo
We should provide a more decent README as this will appear on Artifact Hub

2021-11-10 13:06 UTC, tomkerkhove commented
Can you also provide the `install` section as per https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-pkg.yml#L31 please?

This should help them install the external scaler.

Example: https://artifacthub.io/packages/keptn/keptn-integrations/dynatrace-service?modal=install ([source](https://github.com/keptn-sandbox/artifacthub/blob/main/dynatrace/0.17.0/artifacthub-pkg.yml))

2021-11-10 15:30 UTC, JatinSanghvi commented
Marked PR as draft. I will get the release created and Helm chart ready for the external scaler before working on this one.

2021-11-19 07:06 UTC, tomkerkhove commented
Feel free to let me know if you need help here @JatinSanghvi (but take your time)

2021-11-22 07:45 UTC, tomkerkhove reviewed
LGTM, but let's wait for https://github.com/kedacore/keda-external-scaler-azure-cosmos-db/pull/20 & https://github.com/kedacore/charts/pull/203

2021-11-22 07:45 UTC, tomkerkhove commented on artifacthub/azure-cosmos-db/0.1.0/artifacthub-pkg.yml
> +  - azure-cosmos-db
Let's throw in a new one
```suggestion
  - azure
  - azure-cosmos-db
```

2021-11-22 07:45 UTC, tomkerkhove commented on artifacthub/azure-cosmos-db/0.1.0/artifacthub-pkg.yml
> +    url: https://github.com/kedacore/keda-external-scaler-azure-cosmos-db
Let's add our Helm registry to be complete
```suggestion
links:
  - name: Helm Registry
    url: https://github.com/kedacore/charts
  - name: GitHub
    url: https://github.com/kedacore/keda-external-scaler-azure-cosmos-db
```

2021-11-22 07:45 UTC, tomkerkhove commented on artifacthub/azure-cosmos-db/0.1.0/artifacthub-pkg.yml
> +  Please refer to the [setup instructions](https://github.com/kedacore/keda-external-scaler-azure-cosmos-db#readme) for more details.
Let's align this with our docs from the other PRs when they are merged

2021-11-22 07:45 UTC, tomkerkhove commented on artifacthub/azure-cosmos-db/0.1.0/artifacthub-pkg.yml
> +description: Scale applications based on changes to Azure Cosmos DB container data.
Let's align with Helm chart description

2021-11-22 07:45 UTC, tomkerkhove commented on artifacthub/azure-cosmos-db/0.1.0/artifacthub-pkg.yml
> +name: keda-external-scaler-azure-cosmos-db
Let's align with Helm chart name

2021-11-24 12:35 UTC, tomkerkhove approved these changes
LGTM, thanks a ton!

2021-11-24 12:35 UTC, merged